In [1]:
import torch

In [2]:
t = torch.Tensor()


In [3]:
type(t)

torch.Tensor

In [4]:
print(t.device)
print(t.layout)

cpu
torch.strided


In [5]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

- stride is how tensor is layed out in tensore
- 1 tensor contain uniform type
- tensore computation depend on type and device

In [8]:
data = np.array([1,2,3])
type(data)

<IPython.core.display.Javascript object>

numpy.ndarray

In [9]:
# 1 method
torch.Tensor(data)
#here T is class constructore
#condtructore use global dtype value which is float64 

tensor([1., 2., 3.])

In [10]:
# 2nd
torch.tensor(data)
#here t is small it is Factory function is allow more dynamic object 

tensor([1, 2, 3])

In [11]:
# 3rd
torch.as_tensor(data)

tensor([1, 2, 3])

In [12]:
#4th
torch.from_numpy(data)

tensor([1, 2, 3])

# Basic creation of data

In [13]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [14]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [15]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [16]:
torch.rand(2,2)

tensor([[0.5091, 0.8446],
        [0.2909, 0.6993]])

#  Reshape

In [18]:
t = torch.tensor([
[1,1,1],
[2,2,2],
[3,3,3]])

In [19]:
t.size()

torch.Size([3, 3])

In [20]:
t.shape

torch.Size([3, 3])

In [22]:
torch.tensor(t.shape).prod()

tensor(9)

In [24]:
t.numel() #to count number of element

9

In [25]:
t.reshape(9,)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

# Stack

In [26]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [27]:
t = torch.stack((t1,t2,t3))

In [28]:
t.shape

torch.Size([3, 4, 4])

- 3 is batch
- 4 is width
- 4 is height


In [29]:
t=t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [30]:
t[0]  #batch

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [31]:
t[0][0] #color channel

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [32]:
t[0][0][0] #width

tensor([1, 1, 1, 1])

In [33]:
t[0][0][0][0] #height

tensor(1)

In [35]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [36]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [37]:
t.reshape(-1,4*4)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Elementry wise operation


In [38]:
t1 

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [39]:
t2 

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [40]:
t1 + t2 

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])

In [41]:
t1 - t2 

tensor([[-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1]])

 # Broadcasting

In [52]:
t1 = torch.tensor([
    [1,1],[1,1]
    
])


In [54]:
t1.shape

torch.Size([2, 2])

In [55]:
t2 = torch.tensor([2,4])

In [58]:
t2.shape

torch.Size([2])

In [57]:
t1 + t2 

tensor([[3, 5],
        [3, 5]])

In [59]:
np.broadcast_to(t2.numpy(),t1.shape)

<IPython.core.display.Javascript object>

array([[2, 4],
       [2, 4]])

In [60]:
t1  + t2 

tensor([[3, 5],
        [3, 5]])

# Reduction 

In [66]:
 t1 = torch.tensor([
    [1,1,0,1],
    [1,4,1,1],
    [1,1,5,1],
    [7,0,1,1]
],dtype=torch.float32)

In [67]:
t1.sum()

tensor(27.)

In [68]:
t1.prod()

tensor(0.)

In [69]:
t1.mean()

tensor(1.6875)

In [70]:
t1.std()

tensor(1.9225)

In [71]:
 t2 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
],dtype=torch.float32)

In [72]:
t2.sum()

tensor(24.)

In [73]:
t2.sum(dim=0)

tensor([6., 6., 6., 6.])

In [74]:
t2.sum(dim=1)

tensor([ 4.,  8., 12.])

In [78]:
print(t2[0].sum())
print(t2[1].sum())
print(t2[2].sum())

tensor(4.)
tensor(8.)
tensor(12.)


# ArgmMaX


In [79]:
 t3 = torch.tensor([
    [1,3,1,1],
    [2,2,4,2],
    [3,0,6,3],
],dtype=torch.float32)

In [80]:
t3.max()

tensor(6.)

In [84]:
t3.max(dim=0)

torch.return_types.max(
values=tensor([3., 3., 6., 3.]),
indices=tensor([2, 0, 2, 2]))

In [82]:
t3.argmax() #position of maximum form flatten 

tensor(10)

In [85]:
t3.argmax(dim=0)

tensor([2, 0, 2, 2])

In [86]:
 t3.mean()

tensor(2.3333)

In [87]:
t3.mean().item()

2.3333332538604736

In [90]:
list(t3.mean(dim=0).item())

ValueError: only one element tensors can be converted to Python scalars

In [89]:
t3.mean(dim=0).tolist()

[2.0, 1.6666666269302368, 3.6666667461395264, 2.0]